# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@1
      displayName: Build an image
      inputs:
        containerregistrytype: 'container Registry'
        dockerRegistryEndpoint: dockerRegistryServiceConnection1
        imageName: 'sahilabhishek/docker-python-webapplication:$(Build.BuildId)'
        command: Build an image
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    - task: Docker@1
      displayName: Login
      inputs:
        containerregistrytype: 'container Registry'
        dockerRegistryEndpoint: dockerRegistryServiceConnection1
        command: login
    - task: Docker@1
      displayName: 'Push an image'
      inputs:
        command: push an image
        imageName: 'sahilabhishek/docker-python-webapplication:$(Build.BuildId)'
        tags: |
          $(tag)